// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHV8hG9WiKcPrGYLhA-5da1zB67aN-B5w',
    appId: '1:417162787841:web:da6ad17e435e7cfe909400',
    messagingSenderId: '417162787841',
    projectId: 'socialappflutter-3653b',
    authDomain: 'socialappflutter-3653b.firebaseapp.com',
    storageBucket: 'socialappflutter-3653b.firebasestorage.app',
    measurementId: 'G-03KJHZNDH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj2JCe1ScxV_MvfEBW4MGMCTwLCHhYbFE',
    appId: '1:417162787841:android:af7c175e9ef24e6b909400',
    messagingSenderId: '417162787841',
    projectId: 'socialappflutter-3653b',
    storageBucket: 'socialappflutter-3653b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZqsHUZckSFB2xB9Fe-BqYot170_iNRdc',
    appId: '1:417162787841:ios:952da284390a33de909400',
    messagingSenderId: '417162787841',
    projectId: 'socialappflutter-3653b',
    storageBucket: 'socialappflutter-3653b.firebasestorage.app',
    iosBundleId: 'com.example.socmedAppFlutter',
  );
}
